### ISSUE TITLE
LogiLedSetLightingForTargetZone support

### ISSUE THREAD

**Issue by Smilebags** [fresc81/logiled#3]
Hi, I'm back.

I'm wondering whether there is the ability to target the zones on mice with multiple zones (in particular the G502 which has two zones). I can see there's `setLightingForKeyWithKeyName` which I've done a sweep through all the low values and the higher values (G keys near 0xFFF1 and 0xFFFF1) with no success.

On page 24 of the Logitech LED SDK documentation, there's reference to a function `LogiLedSetLightingForTargetZone` which takes a device type, a zone, and the percentages. I feel like that's exactly what I need, but can't find any reference to it in logiled. The alternatives to `setLighting` such as `setLightingForKeyWithKeyName` don't seem to be suitable for me.

Any direction you could point me in would be much appreciated.
Thanks.

**Comment by fresc81** [comment]
Hi, welcome back.
It looks like I never implemented that function because I don't own a
capable device to test it. But from the looks of it this should not be a
big deal.
I also updated the Logiled SDK to Version 9 and had not yet been able to
check if there are other new funtions in it.
As we are forced to be indoors atm I have some spare time to try
implementing it next weekend.

Hold on and stay safe.

Chris Cook <notifications@github.com> schrieb am Mo., 30. März 2020, 17:07:

**Comment by Smilebags** [comment]
Thanks, I'm also stuck indoors at the moment, happy to give any commits a try to validate that they work.

**Comment by fresc81** [comment]
That was quite easy. Just a bit copy and paste. Jim did a great job with the typescript definitions. You can try out the added function in the master branch, if you like. I'll add tests and stuff next weekend.

**Comment by Smilebags** [comment]
I'm running into some issues building, getting the error 'primordials is not defined'. I can see that the function is now in the type definition but it doesn't seem to be available at runtime, hence me attempting to rebuild.
Out of the box, dist wasn't available so I rebuilt that with `compile`, but trying to rebuild (starting with `configure`) gives me `Cannot find module 'nan'`. I installed that and tried again, continued installing deps as required, but then I ran into the primordials issue - that one I'm not sure how to solve.

**Comment by fresc81** [comment]
I wasn't able to reproduce your problem with the missing nan module and the compilation errors. But I found a missing export when enabling the unit test for the new function which should now be fixed. Also can you try running `npx node-gyp configure --msvs_version=2019 --verbose` ? Assuming you switched using the latest visual studio. Also I run the build process by starting the "Developer PowerShell for VS 2019" and then cd'ing to logiled.

**Comment by Smilebags** [comment]
I will try those steps tomorrow and report back, thanks again.

**Comment by Smilebags** [comment]
Here's the output of the node-gyp command from Developer PowerShell for VS 2019
```
PS H:\Users\chris\Documents\Web Study\logitech-g-control\node_modules\logiled> npx node-gyp configure --msvs_version=2019 --verbose
npx: installed 100 in 6.934s
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\chris\\AppData\\Roaming\\npm-cache\\_npx\\18316\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--msvs_version=2019',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@6.1.0
gyp info using node@13.12.0 | win32 | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - "python3" is not in PATH or produced an error
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "C:\Program Files\Python\3.5.0\python.exe"
gyp verb find Python - executing "C:\Program Files\Python\3.5.0\python.exe" to get version
gyp verb find Python - version is "3.5.0"
gyp info find Python using Python version 3.5.0 found at "C:\Program Files\Python\3.5.0\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 13.12.0
gyp verb command install [ '13.12.0' ]
gyp verb install input version string "13.12.0"
gyp verb install installing version: 13.12.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 13.12.0
gyp verb build dir attempting to create "build" dir: H:\Users\chris\Documents\Web Study\logitech-g-control\node_modules\logiled\build
gyp verb build dir "build" dir needed to be created? null
gyp verb find VS msvs_version was set from command line or npm config
gyp verb find VS - looking for Visual Studio version 2019
gyp verb find VS running in VS Command Prompt, installation path is:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp verb find VS - will only use this version
gyp verb find VS checking VS2019 (16.4.29905.134) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v142
gyp verb find VS - found Windows SDK: 10.0.18362.0
gyp info find VS using VS2019 (16.4.29905.134) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: H:\Users\chris\Documents\Web Study\logitech-g-control\node_modules\logiled\build\config.gypi
gyp verb config.gypi checking for gypi file: H:\Users\chris\Documents\Web Study\logitech-g-control\node_modules\logiled\config.gypi
gyp verb common.gypi checking for gypi file: H:\Users\chris\Documents\Web Study\logitech-g-control\node_modules\logiled\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Program Files\Python\3.5.0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\chris\\AppData\\Roaming\\npm-cache\\_npx\\18316\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'H:\\Users\\chris\\Documents\\Web Study\\logitech-g-control\\node_modules\\logiled\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\chris\\AppData\\Roaming\\npm-cache\\_npx\\18316\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\chris\\AppData\\Local\\node-gyp\\Cache\\13.12.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\chris\\AppData\\Local\\node-gyp\\Cache\\13.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\chris\\AppData\\Roaming\\npm-cache\\_npx\\18316\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\chris\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\13.12.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=H:\\Users\\chris\\Documents\\Web Study\\logitech-g-control\\node_modules\\logiled',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'H:\\Users\\chris\\Documents\\Web Study\\logitech-g-control\\node_modules\\logiled\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- H:\Users\chris\Documents\Web Study\logitech-g-control\node_modules\logiled\[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:131:20)
    at Object.runInThisContext (vm.js:297:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'H:\\Users\\chris\\Documents\\Web Study\\logitech-g-control\\node_modules\\logiled\\[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\chris\AppData\Roaming\npm-cache\_npx\18316\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chris\\AppData\\Roaming\\npm-cache\\_npx\\18316\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--msvs_version=2019" "--verbose"
gyp ERR! cwd H:\Users\chris\Documents\Web Study\logitech-g-control\node_modules\logiled
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
```

**Comment by Smilebags** [comment]
After installing `nan` I was able to run that command. I can see that it is in the dev dependencies, maybe I just missed installing them somehow.

**Comment by Smilebags** [comment]
I'm unfortunately still getting `undefined` for `logiled.setLightingForTargetZone` after successfully running `npm run compile` and `npx node-gyp configure --msvs_version=2019 --verbose`. I'm going to see if I can run the tests, as that should show me whether I have things configured right.

**Comment by Smilebags** [comment]
Definitely seems like everything _else_ is working, and this confirms what I see in my application.
Here's the test output:

```
> npx mocha --require ts-node/register src/*.spec.ts



  logiled
    √ should run on windows
    √ should initialize sdk (367ms)
    √ should get sdk version
    √ should finalize sdk
    per key RGB
      √ should setup keyboard (per key RGB)
      √ should get a numeric config option
      √ should get a boolean config option
      √ should get a color config option
      √ should set config option labels
      √ should save current ligthing
      √ should blink keyboard (red) (5002ms)
      √ should fade keyboard (green) (5001ms)
      √ should set keyboard color (blue) (5001ms)
      √ should stop effects
      √ should restore ligthing
      √ should save lighting for ESC key (251ms)
      √ should blink ESC key (red) (4999ms)
      √ should fade ESC key (green) (5000ms)
      √ should set ESC key color (blue) (5006ms)
      √ should stop effects on ESC key
      √ should restore lighting for ESC key (252ms)
      √ should exclude W,S,A and D keys from bitmap
      √ should exclude existing Int32Array key lists from bitmap
      √ should animate lighting from bitmap (19447ms)
      √ should set NumLock key color (white, by scan code) (5002ms)
      √ should set NumLock key color (black, by hid code) (5002ms)
      √ should set NumLock key color (white, by quartz code) (5001ms)
    RGB
      √ should setup keyboard/mouse (RGB)
      √ should set device color (blue) (5000ms)
      1) should set mouse zone colors (orange and purple)
      √ should blink device (red) (5003ms)
      √ should fade device (green) (5001ms)


  31 passing (1m)
  1 failing

  1) logiled
       RGB
         should set mouse zone colors (orange and purple):
     TypeError: _1.default.setLightingForTargetZone is not a function
      at Context.<anonymous> (src\index.spec.ts:499:28)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by Smilebags** [comment]
Running `npx prebuild --all --strip --arch x64` on Node v13.12 still gives me the error `ReferenceError: primordials is not defined`, which seems to come from out of date dependencies. I wonder whether you have some newer versions of packages or globally installed ones, which aren't included in the package.json file - I installed the deps with `npm ci` so I should have the exact versions of packages in package-lock.json, though I still run into this error.
